### ISSUE TITLE
Book a hostel issue

### ISSUE THREAD

**Issue by pranishbrah** [Manash111/Collab_Development#17]
in the customer dashboard when the room is chosen, seater option was not clicking and same problem with fees per month.
address problem and finally there is no booking option after filling the details.
![image](https://github.com/Manash111/Collab_Development/assets/164293485/7bd46a22-4ef9-4e90-bbc0-66bdf7126de6)

**Comment by 69sarthak69** [comment]
![image](https://github.com/Manash111/Collab_Development/assets/127380488/b846a4b5-c0d7-46eb-b468-18b5dec3beb6)
i have updated my code and fixed the error of not displating the seater and fees  in my book-hostel.php file.
