### ISSUE TITLE
Issue in Change Password

### ISSUE THREAD

**Issue by pranishbrah** [Manash111/Collab_Development#72]
![image](https://github.com/Manash111/Collab_Development/assets/164293485/3ed6faa1-33e9-4686-a47d-82bacb45f0d6)
even if the old password does not match, it does not show the error message.
It must show some error text to user to make it more clear while using the system

**Comment by 69sarthak69** [comment]
![image](https://github.com/Manash111/Collab_Development/assets/127380488/f66b6301-a635-469b-a126-a486ad3ce5ff)
i have updated a code that shows the user if the old password matches or not and also shows that new and re typed new password matches or not
