### ISSUE TITLE
Issue in header

### ISSUE THREAD

**Issue by pranishbrah** [Manash111/Collab_Development#73]
![image](https://github.com/Manash111/Collab_Development/assets/164293485/b057596c-d78d-402c-ba48-e3e382ec395d)
user must be able to easily navigate through the dashboard and landing page of the system.

**Comment by pranishbrah** [comment]
![image](https://github.com/Manash111/Collab_Development/assets/164293485/bec641df-7235-4b87-8f6b-93d24b00492b)
![image](https://github.com/Manash111/Collab_Development/assets/164293485/f1e97fb8-7864-454e-9d74-772ed70a5b6a)
Issue Fixed
when user clicks the text "Hostel Management System", it navigates back to the landing page of the system

**Comment by pranishbrah** [comment]
![image](https://github.com/Manash111/Collab_Development/assets/164293485/bec641df-7235-4b87-8f6b-93d24b00492b)
![image](https://github.com/Manash111/Collab_Development/assets/164293485/f1e97fb8-7864-454e-9d74-772ed70a5b6a)
Issue Fixed
when user clicks the text "Hostel Management System", it navigates back to the landing page of the system

**Comment by Manash111** [comment]
![image](https://github.com/Manash111/Collab_Development/assets/164293485/bec641df-7235-4b87-8f6b-93d24b00492b)
![image](https://github.com/Manash111/Collab_Development/assets/164293485/f1e97fb8-7864-454e-9d74-772ed70a5b6a)
Issue Fixed
when user clicks the text "Hostel Management System", it navigates back to the landing page of the system
