### ISSUE TITLE
Issue in Logout Button(User Dashboard)

### ISSUE THREAD

**Issue by pranishbrah** [Manash111/Collab_Development#74]
![image](https://github.com/Manash111/Collab_Development/assets/164293485/8648c98f-ec13-4a17-bbc7-c304359d6766)
![image](https://github.com/Manash111/Collab_Development/assets/164293485/1d74b8b5-4caa-4df7-af1b-128889c4d0b3)
When logout button is clicked, it does not navigate to the specific page but shows this  "URL not found" error page.

**Comment by 69sarthak69** [comment]
The error occurred when a logged-in user attempted to log out, has been resolved. The necessary corrections have been made to the code, and the functionality now works as intended.
![image](https://github.com/Manash111/Collab_Development/assets/127380488/3b63d743-9a14-4755-a90f-2f886aca5cae)
![image](https://github.com/Manash111/Collab_Development/assets/127380488/b4b08969-3651-4b6d-93f3-0338a5abbeee)
