### ISSUE TITLE
Admin panel 

### ISSUE THREAD

**Issue by pranishbrah** [Manash111/Collab_Development#75]
![image](https://github.com/Manash111/Collab_Development/assets/164293485/db04206a-7348-455b-b255-d37bc60ca8a4)
In this admin panel, admin cannot go back to the main landing page.
easy navigation to landing page should be created

**Comment by pranishbrah** [comment]
![image](https://github.com/Manash111/Collab_Development/assets/164293485/6bfbe973-b17b-4cd4-ae43-1a6fa8c31b53)
![image](https://github.com/Manash111/Collab_Development/assets/164293485/7da64ba5-961a-4adf-ae8e-4d8daa818921)
Issue fixed.
when admin clicks the text "Hostel Management System", it navigates to the landing page of the system.

**Comment by Manash111** [comment]
![image](https://github.com/Manash111/Collab_Development/assets/164293485/6bfbe973-b17b-4cd4-ae43-1a6fa8c31b53)
![image](https://github.com/Manash111/Collab_Development/assets/164293485/7da64ba5-961a-4adf-ae8e-4d8daa818921)
Issue fixed.
when admin clicks the text "Hostel Management System", it navigates to the landing page of the system.
