### ISSUE TITLE
Issue in Contact Button(Landing page)

### ISSUE THREAD

**Issue by pranishbrah** [Manash111/Collab_Development#77]
![image](https://github.com/Manash111/Collab_Development/assets/164293485/c21363a4-4f3e-43d7-9810-86c8216d3293)
every other link works, but contact link is not working.
![image](https://github.com/Manash111/Collab_Development/assets/164293485/611af27a-24c5-400e-93ae-4282b12cbddb)

It should navigate to contact detail section.

**Comment by Manash111** [comment]
![image](https://github.com/Manash111/Collab_Development/assets/76163583/668108dc-7545-4776-aeb8-e6da7e87da5b)
![image](https://github.com/Manash111/Collab_Development/assets/76163583/747c065e-ff72-4f19-8a98-04c11b0948a3)
Issue fixed
it works now when the contact link is clicked
